# Generated by Django 5.1.3 on 2024-12-05 18:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.client')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.doctor')),
            ],
        ),
    ]
